### ISSUE TITLE
Start and Menu not appearing on Android TV 

### ISSUE THREAD

**Issue by yoanrigal** [wolpi/prim-ftpd#123]
Hello,
I now tried your app on another TV box, with Android TV 7.1.2
Menu and Start server button are not appearing ? See screeshot attached.

![2018_01_12_08 40 45](https://user-images.githubusercontent.com/35311509/34894272-008e9988-f7e1-11e7-9295-734c658142f3.png)

**Comment by spec1re** [comment]
Same here with Android TV 6 MM.

**Comment by wolpi** [comment]
I can reproduce it in simulator. It seems like action bar items are not working on android tv at all. The new toolbar might work but that is likely to require a higher min sdk level which will upset users of old android versions. I'll see what can be done.

**Comment by spec1re** [comment]
With my Nvidia Shield TV / Android TV 7 (Nougat), its working fine, maybe Nividia uses a higher API lvl?

Thanks.

**Comment by wolpi** [comment]
Google has quite some docs about supporting android tv. Apps are supposed to provide different layouts and navigation schems as they must be controled with d-pad instead of touchscreen.

It seems to be android tv default to not show action bar icons. But nvidia seems to have overridden that default.

I've added buttons to start/stop server and open preferences in main layout which are made visible when device has no touchscreen (they are gone by default). And I've added a landscape layout.

**Comment by spec1re** [comment]
Working great now, thanks!

**Comment by yoanrigal** [comment]
Absolutely ! Thanks !

**Comment by wolpi** [comment]
🎉 👍 😄
