### ISSUE TITLE
Extremely slow (with SAF).

### ISSUE THREAD

**Issue by nextgenthemes** [wolpi/prim-ftpd#124]
Copperhead OS newest version based on Android 8

I am transferring with only 120 Kb/s.

I can do a speedtest in the browser at the same time and I get 11 Mbit/s so its not my wifi speed thats limiting this.

Also sidenotes.

I am not able to connect with password at all with nautilus or filezilla. Unknown error.

With public key I am able to connect with filezilla when selecting normal login method providing a outdated invalid password (filezilla tries public key first I guess)

Commandline sftp does not work either.

```
$ sftp -P 1234 red@192.168.0.1
ssh: connect to host 192.168.0.1 port 1234: Connection refused
Couldn't read packet: Connection reset by peer
```

**Comment by wolpi** [comment]
Which Storage Type do you use? SAF is known to be slow but necessary to access sd card.
Which version of the app do you have? Selection of storage type is available since 5.0.
Did you try FTP? Users reported SFTP is slow due to encryption overhead and slow CPUs.

To analyze your various sidenotes it would be great if you could post logs.

**Comment by TeutonJon78** [comment]
I can't comment directly to OPs issue, but I was recently testing out various SSH/SFTP servers, and prim-FTP on SAF is noticeably slower than other apps using SAF.

**Comment by nextgenthemes** [comment]
I won't be do anymore testing on this because I no longer need this right now and not doing anything on my phone at this time. I do not know what SAF it but my phone i a nexus 5X that does not have any SD card slot at all this its definitely not because some slow SD card reading. And for version I do knot know but I used what was on fdroid at the time of posting.

**Comment by wolpi** [comment]
Well, SAF is slow as android actually provides 2 different SAF APIs. One of them is slow. This app uses the slow one for read/write access as I had issues using the fast one to create new files and directories. Contributions welcome :wink:. That's why this app provides read-only SAF, that one uses the fast SAF API.

**Comment by wolpi** [comment]
closing as SAF is a never ending story and it is not likely that this could be fixed
