### ISSUE TITLE
How to use prim-ftpd

### ISSUE THREAD

**Issue by joshcangit** [wolpi/prim-ftpd#184]
## Questions
So far I only know how to set it up to use **FTP only** with **anonymous login**. I can't find any documentation, guide, help or tips on how to use **prim-ftpd**

### Username and password
I'm not sure if the settings for the username and password work. In older versions, they weren't actually configurable and if changed would cause both FTP and SFTP to be inaccessible unless the app was reinstalled. So it was fixed in a recent version?

### SFTP
I don't know why I can't connect to the SFTP port. I wonder what are the settings needed to makes sure the SFTP port is accessible?

### Public Key Authentication
It generates keys for SFTP but can I use my own keys instead? If yes, then how to do it?

### Hostname resolution
I couldn't find anything on Android that does it but is it possible to connect to FTP, also SFTP, using a hostname? If no, would it be possible in future?

**Comment by wolpi** [comment]
> Username and password

With these you can set a username and password which is used by both servers (ftp and sftp). I never heard about that didn't work in older versions. If it does not work for you, share logs, please.

> SFTP

Well, you should just start server and connect to it :wink:. It would be helpful when you share screenshots how main screen and settings screen looks like. A screenshot of your client, as you try to connect, would be helpful, too.


> Pub key auth

Key generated by app has nothing to do with pub key auth. Generated key is a server key required to sftp encryption to work. App shows fingerprints of that key in order to allow you to verify you connect to correct server (avoid man in middle attacks).
For pub key auth you must use your own key. Otherwise it would not make sense. Therefore you have to place your public key in a file on your device. The settings screen tells you the path.


> Hostname resolution

That must be handled on network level. The app has no way to do something with hostnames.
