### ISSUE TITLE
Material design Icon

### ISSUE THREAD

**Issue by xphnx** [wolpi/prim-ftpd#28]
Hello!
Thank you for your work, the app has greatly improved.
I made a new material design style icon, if you want to change

![ic_launcher_materialhdpi](https://cloud.githubusercontent.com/assets/4024412/9245408/17e07f02-41a4-11e5-8052-760e5196c35e.png)
![ic_launcher_materialmdpi](https://cloud.githubusercontent.com/assets/4024412/9245407/17e030ec-41a4-11e5-8195-e21c13734376.png)
![ic_launcher_materialstore](https://cloud.githubusercontent.com/assets/4024412/9245411/17e552fc-41a4-11e5-8d35-66eee445b039.png)
![ic_launcher_materialxhdpi](https://cloud.githubusercontent.com/assets/4024412/9245409/17e29792-41a4-11e5-9c62-aba7ba02bc8c.png)
![ic_launcher_materialxxhdpi](https://cloud.githubusercontent.com/assets/4024412/9245406/17ddca1e-41a4-11e5-8b49-2be5291925ee.png)
![ic_launcher_materialxxxhdpi](https://cloud.githubusercontent.com/assets/4024412/9245410/17e3bcee-41a4-11e5-9ea1-f06ad9111df2.png)

.
A greeting.

**Comment by xphnx** [comment]
Another version:
![ic_launcher2_materialhdpi](https://cloud.githubusercontent.com/assets/4024412/9246118/9c3d14e0-41a9-11e5-845c-f3a7d2379beb.png)
![ic_launcher2_materialmdpi](https://cloud.githubusercontent.com/assets/4024412/9246115/9c3a4fd0-41a9-11e5-8f7f-a846609a0f31.png)
![ic_launcher2_materialstore](https://cloud.githubusercontent.com/assets/4024412/9246113/9c365c90-41a9-11e5-92bc-307856e503a5.png)
![ic_launcher2_materialxhdpi](https://cloud.githubusercontent.com/assets/4024412/9246117/9c3c68e2-41a9-11e5-8b1c-28eadee315b9.png)
![ic_launcher2_materialxxhdpi](https://cloud.githubusercontent.com/assets/4024412/9246116/9c3c0be0-41a9-11e5-8a2c-6041487c5cdc.png)
![ic_launcher2_materialxxxhdpi](https://cloud.githubusercontent.com/assets/4024412/9246114/9c39f6e8-41a9-11e5-8337-938e1c7bed83.png)

**Comment by wp9015362** [comment]
@xphnx :

IMHO the second version looks better.

It looks really nice and definitely better than the current icon (IMHO).

It would be nice if @wolpi would accept it.

Also, if this icon gets accepted, then I think the theme of the app additionaly should adopt the colors of the icon.

So, the toolbar for example could be made to have the same blue color as the icon. And the play/pause button could be made to have the same purple color that is also present in the icon.

Also, there is a related issue:

https://github.com/wolpi/prim-ftpd/issues/23

Regards

**Comment by wolpi** [comment]
:+1: 

Wow, yes I like it a lot !
I also prefer the 2nd version.

Just one thing: google play requires the icon with 512x512 pixels. Could you add that?

> the theme of the app additionaly should adopt the colors of the icon.

I'll check how much work it is to do custom theming. And as there is now a preference to switch between dark and light theme, it is necessary to do the custom theming twice.


> And the play/pause button could be made to have the same purple color

Are you guys able to create such icons?
With own icons we could also use a stop icon instead of pause and use something different for preferences. Currently I use android system icons as I am no artist.
Of course we would need a dark and light version for each of these icons.


As I keep saying in other issues: It takes some time until I can work on this project again.

**Comment by xphnx** [comment]
Sure! I will add the 512x512. (sorry, I think it was 500x500...)
I can also do some icons for play, stop, preferences... in dark and light.

**Comment by xphnx** [comment]
Here you have an icon pack: launcher icon, actionbar icons, notification icon. https://my.owndrive.com/index.php/s/VjqwOLAwaccGdp5

The designs are from Google icons, adapted following material design guidelines. Hope sizes are correct, otherwise let me know and I will change it. 

As the icons are provided by Google I think its probably would be avaliable via some library for Lollipop. You can take a look at https://google.github.io/material-design-icons/

For theming the app I think it must be done choosing a primary color and an accent color and customizing the app color palette http://www.google.com/design/spec/style/color.html#color-ui-color-application https://developer.android.com/training/material/theme.html#ColorPalette (thats why the action bar icons have a transparent background)

If you want to choose purple color (#9c27b0) for action bar as a primary color, then you need to choose an accent color with sufficiently contrast with the background color. The status bar must have the 700 tint of the primary color (#7b1fa2 for purple). Im not sure if the purple is the most appropriate for the dark theme, but maybe you could use in this case, light-blue500.

If you need some more help with icons, feel free to ask for. I follow your activityline.

**Comment by wp9015362** [comment]
> @xphnx wrote:
> 
> Here you have an icon pack: launcher icon, actionbar icons,

Nice! Those look a lot better than the current icons. And the third version of the launcher icon that you have included looks even better than the second version!

And the preference icon with the three dots is exactly what I was about to suggest! Really nice!

But when this preference icon with the three dots will be used, then I think pressing on that icon should no longer lead directly to the settings.

Instead, when pressing on that icon, a small submenu should open from the upper right corner of the screen, which would then offer to go either to the settings or to the [about section](https://github.com/wolpi/prim-ftpd/issues/25).

It's done like that in almost all Material Design apps which have such an icon with the three dots (including the official Google apps).

So I'd say primitive ftpd should do it like this as well if it will use the preference icon with the three dots (which it should IMHO).

> @xphnx wrote:
> 
> notification icon

I don't think the notification icon is perfect. Because the upper right corner of the notification icon looks like the upper right corner of the first version of the launcher icon which you have posted here.

IMHO it should rather look like (match) the second/third version of the launcher icon.

> @xphnx wrote:
> 
> As the icons are provided by Google I think its probably would be avaliable via some library for Lollipop. You can take a look at https://google.github.io/material-design-icons/

Yeah, it sounds reasonable to use official Material Design icons to have a consistent look across apps :+1: .

> @xphnx wrote:
> If you want to choose purple color (#9c27b0) for action bar as a primary color, then you need to choose an accent color with sufficiently contrast with the background color. The status bar must have the 700 tint of the primary color (#7b1fa2 for purple). Im not sure if the purple is the most appropriate for the dark theme, but maybe you could use in this case, light-blue500.

IMHO the primary color of the actionbar should not be purple.

Blue would be better.

Regards

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by wp9015362** [comment]
> @wolpi wrote:
> 
> I'll check how much work it is to do custom theming. And as there is now a preference to switch between dark and light theme, it is necessary to do the custom theming twice.

Just saying:

Another open source Android app which I know of and which allows to switch between different themes, is the official Kodi remote app, called "Kore", see:

https://github.com/xbmc/Kore
https://play.google.com/store/apps/details?id=org.xbmc.kore

TextSecure also allows to switch between themes:

https://github.com/WhisperSystems/TextSecure
https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

Regards

**Comment by wp9015362** [comment]
Another app that has very nice theme customizability is Amaze File Manager:

https://github.com/arpitkh96/AmazeFileManager
https://play.google.com/store/apps/details?id=com.amaze.filemanager

Regards

**Comment by wolpi** [comment]
![screenshot_1_android4_dark](https://cloud.githubusercontent.com/assets/1812560/10823328/830e4234-7e5b-11e5-8d62-3cde55daa42a.png)
![screenshot_2_android4_light](https://cloud.githubusercontent.com/assets/1812560/10823332/85756fac-7e5b-11e5-9d5f-0abaf53d43a8.png)

Here are 2 screenshots of the current state. Both are from android4. As you can see I took purple. Just because with blue the icon would not be visible. But a lighter or darker blue could be used instead. And the refresh Icon is quite big. That could be changed as well.

I did not use the "3 dots icon" for preferences as I want to stick to current behaviour for now (preferences screen is opened without "side menu").

What do you think?

And thanks for your ideas/comments/icons so far!

**Comment by wp9015362** [comment]
Thank you.

> @wolpi wrote:
> 
> What do you think?

I think the icons on the action bar should always be white in both the dark theme, as well as in the light theme. The "primitive ftpd" text should also be white in the light theme. That would make for a much better contrast.

All apps that I know of are doing it like that.

Making the icons have another color than full white or full black would also be against the Google Material Design Guidelines, because icons with reduced opacity are considered to be "inactive", see the "Color" section at the bottom of the following page:

https://www.google.com/design/spec/style/icons.html#icons-system-icons

Also, the statusbar also needs to be colored, see:

https://www.google.com/design/spec/style/color.html#color-ui-color-application

I am not sure if it is not colored in your screenshots because you chose to do it like that or if it's just because it's not supported on Android 4.x though.

Also:

I realize that I was the one who submitted https://github.com/wolpi/prim-ftpd/issues/23, but I think the icon should not be on the action bar. Actually most Material Design apps do not show an app icon on the action bar and as you already said, it's hard to put the icon on the colored action bar and still make it properly visible, so I'd say the icon on the action bar should simply be removed.

Regards

**Comment by wolpi** [comment]
@wp9015362

Yes, all in all you are right:
* Having black text in light theme is an android default. But as we changed the background colour it makes sense to adjust text colour, too. That also affects icon colour.
* That icons had some transparence was because they were Holo-Icons. Now I switched to Material-Icons which are plain white (or black but they are not in use, except refresh in light theme)
* The statusbar is coloured since android 5.1. That happens now for this app, too.


So here are new screenshots for all four combinations of android versions and themes
-
android 4, dark theme
--
![android4-dark-1-main-not-running](https://cloud.githubusercontent.com/assets/1812560/11165089/7b688a38-8b05-11e5-8879-8c81db2d75b9.png)
![android4-dark-2-main-running](https://cloud.githubusercontent.com/assets/1812560/11165091/7de4957c-8b05-11e5-8466-edbd061ea49b.png)
![android4-dark-3-prefs](https://cloud.githubusercontent.com/assets/1812560/11165092/81826df8-8b05-11e5-847b-91f3669f7def.png)
![android4-dark-4-notification](https://cloud.githubusercontent.com/assets/1812560/11165093/843aa9f2-8b05-11e5-87f3-4416e22d6515.png)

android 4, light theme
--
![android4-light-1-main-not-running](https://cloud.githubusercontent.com/assets/1812560/11165096/8eb0a9fe-8b05-11e5-991a-2dc630949ab2.png)
![android4-light-2-main-running](https://cloud.githubusercontent.com/assets/1812560/11165097/90f1914c-8b05-11e5-9173-88bc0007cebc.png)
![android4-light-3-prefs](https://cloud.githubusercontent.com/assets/1812560/11165099/932eb44e-8b05-11e5-9fa8-5f11089c9822.png)

android 5, dark theme
--
![android5-dark-1-main-not-running](https://cloud.githubusercontent.com/assets/1812560/11165100/9dbc9ef8-8b05-11e5-850f-78176386bda0.png)
![android5-dark-2-main-running](https://cloud.githubusercontent.com/assets/1812560/11165102/9fad7f34-8b05-11e5-91d0-64771c380fff.png)
![android5-dark-3-prefs](https://cloud.githubusercontent.com/assets/1812560/11165104/a1bda70e-8b05-11e5-8fb4-04ceef02780d.png)
![android5-dark-4-notification](https://cloud.githubusercontent.com/assets/1812560/11165105/a39f3a74-8b05-11e5-87ac-8b10b2fc6b62.png)
(you can also see the new and shiny widget here :smile: )

android 5, light theme
--
![android5-light-1-main-not-running](https://cloud.githubusercontent.com/assets/1812560/11165107/aca7bcea-8b05-11e5-8d8c-7fc8daf27e04.png)
![android5-light-2-main-running](https://cloud.githubusercontent.com/assets/1812560/11165108/ae51edcc-8b05-11e5-9511-c8b67462f891.png)
![android5-light-3-prefs](https://cloud.githubusercontent.com/assets/1812560/11165109/b02a563e-8b05-11e5-8326-bce2feb8e1ea.png)

**Comment by wp9015362** [comment]
@wolpi :

That looks much better :+1: (judging by your screenshots).

Regards

**Comment by wolpi** [comment]
alright, release is on going ...

**Comment by wp9015362** [comment]
@wolpi :

Thank you for the update. But I noticed one issue:

In your screenshots that you have posted in the previous comment, the play/stop/gear icons in the actionbar have the proper size (they have the same size as the [back arrow](https://github.com/wolpi/prim-ftpd/issues/39)).

But on my device the play/stop/gear icons are way too big. On my device the [back arrow](https://github.com/wolpi/prim-ftpd/issues/39) also has the proper size, just as in your screenshots. But the play/stop/gear icons are way bigger than the [back arrow](https://github.com/wolpi/prim-ftpd/issues/39) on my device.

Any chance you could fix that?

**Comment by wp9015362** [comment]
@wolpi :

PS: Here's a screenshot showing the issue:

![Image](https://cloud.githubusercontent.com/assets/7558360/12146836/3cbe9fba-b496-11e5-802e-602f2110691d.png)

As you can see, the play/stop/gear icons are way bigger than the [back arrow](https://github.com/wolpi/prim-ftpd/issues/39).

**Comment by wolpi** [comment]
Now it uses a smaller icon
